# Hyperparameter tuning 

Hyperparameters directly control model structure, function, and performance. Hyperparameter tuning allows data scientists to tweak model performance for optimal results. This process is an essential part of machine learning, and choosing appropriate hyperparameter values is crucial for success.

In [1]:
from sklearn import datasets

In [4]:
iris =datasets.load_iris()

In [5]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.2)

In [19]:
from sklearn import svm

In [20]:
model =svm.SVC(kernel='rbf',C=10,gamma='auto')

In [21]:
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9333333333333333

cross_val_score ( Basically it is KFold , splits the data and calculate the score for each )
It splits the data set into multiple subsets of training and testing data, trains the model on each training subset, performs predictions on the testing subset, and outputs the prediction accuracy score for each subset.

In [22]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5) # cv ---> reprsents the no. of folds or spliting of data

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [25]:
cross_val_score(svm.SVC(kernel='linear',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [27]:
cross_val_score(svm.SVC(kernel='poly',C=30,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [35]:
# same above process using for loop
import numpy as np
kernal =["rbf","linear"]
C=[1,13,20]
avg = {}
for k in kernal:
    for c in C:
        cv_score =cross_val_score(svm.SVC(kernel=k,C=c,gamma='auto'),iris.data,iris.target,cv=5)
        avg[k," ",str(c)]=np.average(cv_score)
avg

{('rbf', ' ', '1'): 0.9800000000000001,
 ('rbf', ' ', '13'): 0.9800000000000001,
 ('rbf', ' ', '20'): 0.9666666666666668,
 ('linear', ' ', '1'): 0.9800000000000001,
 ('linear', ' ', '13'): 0.9733333333333334,
 ('linear', ' ', '20'): 0.9666666666666666}

Grid Search is a conventional algorithm used in machine learning for hyperparameter tuning. It exhaustively tries every combination of the provided hyper-parameter values in order to find the best model.

In [36]:
from sklearn.model_selection import GridSearchCV

In [37]:
clf =GridSearchCV(svm.SVC(gamma='auto'),{
    'C' : [1,10,20],
    'kernel' : ["rbf","linear"]
},cv=5 )

In [39]:
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [40]:
clf.cv_results_

{'mean_fit_time': array([0.0015017 , 0.00136108, 0.00170884, 0.        , 0.00137773,
        0.00417266]),
 'std_fit_time': array([0.00300341, 0.00119098, 0.00240137, 0.        , 0.00208555,
        0.00511066]),
 'mean_score_time': array([0.00161724, 0.00104403, 0.0023963 , 0.00240378, 0.00135808,
        0.        ]),
 'std_score_time': array([0.00323448, 0.00117459, 0.00198761, 0.00480757, 0.00271616,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [43]:
import pandas as pd
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001502      0.003003         0.001617        0.003234       1   
1       0.001361      0.001191         0.001044        0.001175       1   
2       0.001709      0.002401         0.002396        0.001988      10   
3       0.000000      0.000000         0.002404        0.004808      10   
4       0.001378      0.002086         0.001358        0.002716      20   
5       0.004173      0.005111         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [45]:
df=df[['param_C','param_kernel','mean_test_score']]
df

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [46]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [47]:
clf.best_score_

0.9800000000000001

In [48]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

Taking parameters randomy , we have any no. of combinations

In [50]:
from sklearn.model_selection import RandomizedSearchCV 

In [52]:
rs =RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C' : [1,10,20],
    'kernel' : ["rbf","linear"]
},cv=5,n_iter=2 )  # n_iter ---> for no. random combinations

In [53]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [54]:
rs.cv_results_

{'mean_fit_time': array([0.00275035, 0.00220294]),
 'std_fit_time': array([0.00042487, 0.00042397]),
 'mean_score_time': array([0.00187979, 0.00164671]),
 'std_score_time': array([0.00045207, 0.00049591]),
 'param_kernel': masked_array(data=['rbf', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[1, 20],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 1}, {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([0.96666667, 1.        ]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       ]),
 'split3_test_score': array([0.96666667, 0.93333333]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.98      , 0.96666667]),
 'std_test_score': array([0.01632993, 0.0421637 ]),
 'rank_test_score': array([1, 2])}

In [55]:
df1  = pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]
df1

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1      20       linear         0.966667