# K Fold cross-validation

from sklearn.datasets import load_digits

In [7]:
digits =load_digits()

In [8]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

##### Checking accuracy of RandomForestClassifier

In [11]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(digits.data,digits.target,test_size=0.2)

In [17]:
model.fit(x_train,y_train)

C:\Users\Rohan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
model.score(x_test,y_test)

0.975

##### Checking accuracy of RandomForestClassifier

In [45]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()

In [46]:
model2.fit(x_train,y_train)

RandomForestClassifier()

In [47]:
model2.score(x_test,y_test)

0.9776536312849162

### Simple example how its converts the data into specificc no. of folds

In [43]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,shuffle=True, random_state=42)
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [35]:
for tarin_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(tarin_index,test_index)

[0 2 3 4 5 6 8] [1 7]
[1 2 3 4 6 7 8] [0 5]
[0 1 3 4 5 6 7] [2 8]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 5 7 8] [6]


### Now using KFold for digits dataset For LogisticRegression

In [40]:
for tarin_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[tarin_index],digits.data[test_index],digits.target[tarin_index],digits.target[test_index]

In [41]:
model.fit(x_train,y_train)

C:\Users\Rohan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [42]:
model.score(x_test,y_test)

0.9441340782122905

#### KFold for Random Forest

In [48]:
for tarin_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[tarin_index],digits.data[test_index],digits.target[tarin_index],digits.target[test_index]

In [49]:
model2.fit(x_train,y_train)

RandomForestClassifier()

In [52]:
accuracy=model2.score(x_test,y_test)

In [51]:
import numpy as np

In [53]:
print(np.mean(accuracy))

0.9805013927576601


## It performing Good For Random Forest